name: Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    name: Build and Create Tagged Release
    runs-on: ubuntu-latest
    steps:
      - name: Install archive tools
        run: sudo apt install zip

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install
        working-directory: web

      - name: Install package dependencies
        run: npm install
        working-directory: web

      - name: Run build
        run: npm run build
        working-directory: web
        env:
          CI: false

      - name: Update branch
        working-directory: ./
        run: git push origin HEAD:main

      # - name: Update tag ref
      #   uses: EndBug/latest-tag@latest 
      #   with:
      #     ref: ${{ github.ref_name }}
          
      - name: Bundle files
        run: |
          mkdir -p ./temp/clean_multijob
          mkdir -p ./temp/clean_multijob/web/
          cp ./{readme.md,fxmanifest.lua,config.lua} ./temp/clean_multijob
          cp -r ./src ./temp/clean_multijob
          cp -r ./web/build ./temp/clean_multijob/web/
          cd ./temp && zip -r ../clean_multijob.zip ./clean_multijob

      - name: Create Release
        uses: 'marvinpinto/action-automatic-releases@v1.2.1'
        id: auto_release
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          title: 'Latest Build'
          prerelease: false
          files: clean_multijob.zip
          automatic_release_tag: 'latest_production'

        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
